# Number of parameters: 213
# Number of species: 47

### Define independent and dependent variables
@variables t CAMPdegr(t) EIICB(t) cAMP(t) OAA(t) Eno(t) PYR(t) Mdh(t) Cra(t) Icd_P(t) Ppc(t) PEP(t) GLX(t) AceK(t) Me(t) FBP(t) GLC(t) Cya(t) Acoa2act(t) BM(t) ACT(t) EIIA_P(t) AKG(t) ICT(t) Fdp(t) ACoA(t) GltA(t) PdhRPYR(t) MAL(t) Pdh(t) Crp(t) Akg2mal(t) PpsA(t) G6P(t) PckA(t) CraFBP(t) Icd(t) PykF(t) EIIA(t) PG3(t) PfkA(t) IclR(t) PdhR(t) CrpcAMP(t) AceA(t) Acs(t) Emp(t) AceB(t)

### Define parameters
@parameters e_AceK_Kpyr e_CAMPdegr_kcat g_emp_Kcrp e_PpsA_L e_Acs_Kact e_Icd_kcat g_akg2mal_n e_Pdh_L g_pykF_vcra_bound e_Icd_Kict g_ppsA_Kcra e_PfkA_L g_pfkA_vcra_bound g_ppsA_vcra_bound e_Ppc_Kfbp bm_ACT_PYR g_aceBAK_DNA bm_GLC_OAA e_Ppc_L e_Mdh_Kmal bm_GLC_AKG g_icd_vcra_bound g_mdh_vcrp_bound g_aceBAK_kcat_iclr bm_muACT g_mdh_vcrp_unbound e_Eno_Kpep e_AceB_Kglx e_Acoa2act_Kpyr e_AceK_kcat_ph e_AceK_Kpep bm_ACT_PEP bm_GLC_G6P e_Pdh_KpyrI g_akg2mal_vcrp_unbound e_Me_kcat g_fdp_Kcra tf_PdhR_kpyr e_GltA_Kacoa e_Mdh_kcat e_AceK_kcat_ki e_Eno_Kpg3 e_AceK_Kict e_CAMPdegr_KcAMP e_AceK_Koaa g_mdh_Kcrp g_pdh_vpdhr_unbound e_AceK_Kakg e_PckA_Koaa e_PckA_Kpep pts_km1 g_aceBAK_Kcra e_AceB_Kacoa env_M_GLC g_pdh_vpdhr_bound e_Icd_L g_akg2mal_Kcrp e_Me_Kmal e_AceB_kcat g_pfkA_vcra_unbound e_Eno_kcatf e_PfkA_kcat GLC_2 e_Fdp_n g_aceBAK_aceKfactor e_Icd_Kpep g_gltA_vcrp_bound e_Acs_kcat g_aceBAK_vcrp_bound g_icd_Kcra GLC_1 e_AceA_Kict e_Mdh_n e_Ppc_n e_Fdp_L e_Me_Kacoa g_emp_vcra_unbound e_Cya_kcat g_acs_n e_PykF_Kfbp g_icd_vcra_unbound e_AceA_L e_AceA_Kpg3 bm_ACT_G6P bm_GLC_PG3 g_aceBAK_Kcrp g_eno_Kcra g_pykF_vcra_unbound g_emp_Kcra bm_GLC_ACoA e_Me_n g_aceBAK_aceBfactor e_Icd_n g_emp_vcrp_bound e_Emp_kcat_r g_aceBAK_KDNA g_aceBAK_L e_Acoa2act_kcat bm_ACT_PG3 e_Me_Kcamp pts_KEIIA e_Fdp_Kpep BM_2 ACT_1 e_AceA_n e_AceB_Kglxacoa pts_Kglc e_AceK_Kpg3 g_aceBAK_KG e_Pdh_Kpyr e_Acoa2act_L g_eno_vcra_unbound e_AceK_Kicd g_acs_Kcrp e_AceK_n bm_ACT_AKG bm_GLC_PYR e_PckA_kcat e_AceA_kcat e_PykF_L tf_Cra_scale ACT_2 e_PykF_n g_pckA_Kcra g_gltA_Kcrp e_PpsA_n tf_PdhR_scale g_aceBAK_KPprime g_fdp_vcra_unbound BM_1 g_ppsA_vcra_unbound g_pykF_Kcra e_Emp_Kpg3 g_gltA_n e_PykF_Kpep bm_GLC_PEP g_aceBAK_vcrp_unbound e_PfkA_Kg6p e_Cya_KEIIA e_Acoa2act_n e_Emp_kcat_f g_aceBAK_vcra_unbound e_Ppc_kcat e_GltA_Koaaacoa tf_Crp_kcamp env_uc g_akg2mal_vcrp_bound e_AceA_Kakg e_PpsA_Kpyr e_AceK_Kicd_P g_pckA_vcra_bound e_Fdp_Kfbp e_AceK_L g_emp_vcrp_unbound e_Akg2mal_kcat e_GltA_Koaa e_Me_L tf_Cra_n g_emp_vcra_bound e_Pdh_kcat e_Akg2mal_Kakg g_pckA_vcra_unbound e_Ppc_Kpep e_Pdh_n bm_ACT_OAA bm_k_expr g_pfkA_Kcra e_Eno_kcatr tf_Cra_kfbp e_Emp_Kfbp g_fdp_vcra_bound e_PykF_kcat e_PfkA_n g_pdh_Kpdhr g_acs_vcrp_bound pts_k1 tf_Crp_scale tf_PdhR_n g_acs_vcrp_unbound env_M_ACT e_AceK_Kglx e_GltA_Kakg pts_k4 e_Fdp_kcat tf_Crp_n g_eno_vcra_bound bm_muGLC g_aceBAK_KP shift1 e_PfkA_Kpep g_gltA_vcrp_unbound d_k_degr e_PpsA_Kpep bm_ACT_ACoA e_PpsA_kcat e_AceA_Kpep g_aceBAK_vcra_bound shift2 e_Acoa2act_Kacoa e_GltA_kcat e_Pdh_Kglx

### Define constants
@parameters Environment Cell

### Define an operator for the differentiation w.r.t. time
D = Differential(t)

### Events ###
continuous_events = [
[t ~ 3600 * shift1] => [GLC ~ GLC_1, ACT ~ ACT_1, BM ~ BM_1], [t ~ 3600 * shift2] => [GLC ~ GLC_2, ACT ~ ACT_2, BM ~ BM_2]
]

### Function definitions ###
mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) = alphaGLC(GLC, pts_Kglc) * bm_muGLC + alphaACT(ACT, e_Acs_Kact, GLC, pts_Kglc) * bm_muACT
@register mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT)
alphaACT(ACT, e_Acs_Kact, GLC, pts_Kglc) = ACT / (ACT + e_Acs_Kact) * (1 - GLC / (GLC + pts_Kglc))
@register alphaACT(ACT, e_Acs_Kact, GLC, pts_Kglc)
SS_Ppc(GLC, pts_Kglc, ACT, e_Acs_Kact) = alphaGLC(GLC, pts_Kglc) * 0.000999714 + alphaACT(ACT, e_Acs_Kact, GLC, pts_Kglc) * 0.000279893
@register SS_Ppc(GLC, pts_Kglc, ACT, e_Acs_Kact)
k_bm_PG3(GLC, pts_Kglc, bm_GLC_PG3, ACT, e_Acs_Kact, bm_ACT_PG3) = alphaGLC(GLC, pts_Kglc) * bm_GLC_PG3 + alphaACT(ACT, e_Acs_Kact, GLC, pts_Kglc) * bm_ACT_PG3
@register k_bm_PG3(GLC, pts_Kglc, bm_GLC_PG3, ACT, e_Acs_Kact, bm_ACT_PG3)
k_bm_AKG(GLC, pts_Kglc, bm_GLC_AKG, ACT, e_Acs_Kact, bm_ACT_AKG) = alphaGLC(GLC, pts_Kglc) * bm_GLC_AKG + alphaACT(ACT, e_Acs_Kact, GLC, pts_Kglc) * bm_ACT_AKG
@register k_bm_AKG(GLC, pts_Kglc, bm_GLC_AKG, ACT, e_Acs_Kact, bm_ACT_AKG)
k_bm_PEP(GLC, pts_Kglc, bm_GLC_PEP, ACT, e_Acs_Kact, bm_ACT_PEP) = alphaGLC(GLC, pts_Kglc) * bm_GLC_PEP + alphaACT(ACT, e_Acs_Kact, GLC, pts_Kglc) * bm_ACT_PEP
@register k_bm_PEP(GLC, pts_Kglc, bm_GLC_PEP, ACT, e_Acs_Kact, bm_ACT_PEP)
k_bm_ACoA(GLC, pts_Kglc, bm_GLC_ACoA, ACT, e_Acs_Kact, bm_ACT_ACoA) = alphaGLC(GLC, pts_Kglc) * bm_GLC_ACoA + alphaACT(ACT, e_Acs_Kact, GLC, pts_Kglc) * bm_ACT_ACoA
@register k_bm_ACoA(GLC, pts_Kglc, bm_GLC_ACoA, ACT, e_Acs_Kact, bm_ACT_ACoA)
k_bm_PYR(GLC, pts_Kglc, bm_GLC_PYR, ACT, e_Acs_Kact, bm_ACT_PYR) = alphaGLC(GLC, pts_Kglc) * bm_GLC_PYR + alphaACT(ACT, e_Acs_Kact, GLC, pts_Kglc) * bm_ACT_PYR
@register k_bm_PYR(GLC, pts_Kglc, bm_GLC_PYR, ACT, e_Acs_Kact, bm_ACT_PYR)
k_bm_OAA(GLC, pts_Kglc, bm_GLC_OAA, ACT, e_Acs_Kact, bm_ACT_OAA) = alphaGLC(GLC, pts_Kglc) * bm_GLC_OAA + alphaACT(ACT, e_Acs_Kact, GLC, pts_Kglc) * bm_ACT_OAA
@register k_bm_OAA(GLC, pts_Kglc, bm_GLC_OAA, ACT, e_Acs_Kact, bm_ACT_OAA)
k_bm_G6P(GLC, pts_Kglc, bm_GLC_G6P, ACT, e_Acs_Kact, bm_ACT_G6P) = alphaGLC(GLC, pts_Kglc) * bm_GLC_G6P + alphaACT(ACT, e_Acs_Kact, GLC, pts_Kglc) * bm_ACT_G6P
@register k_bm_G6P(GLC, pts_Kglc, bm_GLC_G6P, ACT, e_Acs_Kact, bm_ACT_G6P)
alphaGLC(GLC, pts_Kglc) = GLC / (GLC + pts_Kglc)
@register alphaGLC(GLC, pts_Kglc)
SS_Me(GLC, pts_Kglc, ACT, e_Acs_Kact) = alphaGLC(GLC, pts_Kglc) * 0.000999714 + alphaACT(ACT, e_Acs_Kact, GLC, pts_Kglc) * 0.003399346
@register SS_Me(GLC, pts_Kglc, ACT, e_Acs_Kact)

### Derivatives ###
eqs = [
D(CAMPdegr) ~ +1.0 * (0)-1.0 * (0),
D(EIICB) ~ +1.0 * (0)-1.0 * (0),
D(cAMP) ~ -1.0 * (e_CAMPdegr_kcat * CAMPdegr * cAMP / (cAMP + e_CAMPdegr_KcAMP))+1.0 * (e_Cya_kcat * Cya * EIIA_P / (EIIA_P + e_Cya_KEIIA))-1.0 * (mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * cAMP),
D(OAA) ~ -1.0 * (k_bm_OAA(GLC, pts_Kglc, bm_GLC_OAA, ACT, e_Acs_Kact, bm_ACT_OAA) * OAA)-1.0 * (GltA * e_GltA_kcat * OAA * ACoA / ((1 + AKG / e_GltA_Kakg) * e_GltA_Koaaacoa * e_GltA_Kacoa + e_GltA_Kacoa * OAA + (1 + AKG / e_GltA_Kakg) * e_GltA_Koaa * ACoA + OAA * ACoA))+1.0 * (Mdh * e_Mdh_kcat * (MAL)^(e_Mdh_n) / ((MAL)^(e_Mdh_n) + (e_Mdh_Kmal)^(e_Mdh_n)))-1.0 * (PckA * e_PckA_kcat * OAA / (OAA + e_PckA_Koaa * (1 + PEP / e_PckA_Kpep)))+1.0 * (Ppc * e_Ppc_kcat * PEP / e_Ppc_Kpep * (1 + PEP / e_Ppc_Kpep)^(e_Ppc_n - 1) / ((1 + PEP / e_Ppc_Kpep)^(e_Ppc_n) + e_Ppc_L / (1 + FBP / e_Ppc_Kfbp)^(e_Ppc_n)))-1.0 * (mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * OAA),
D(Eno) ~ +1.0 * (bm_k_expr * mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ((1 - Cra / (Cra + g_eno_Kcra)) * g_eno_vcra_unbound + Cra / (Cra + g_eno_Kcra) * g_eno_vcra_bound))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * Eno),
D(PYR) ~ -1.0 * (k_bm_PYR(GLC, pts_Kglc, bm_GLC_PYR, ACT, e_Acs_Kact, bm_ACT_PYR) * PYR)+1.0 * (pts_k1 * PEP * EIIA - pts_km1 * PYR * EIIA_P)+1.0 * (Me * e_Me_kcat * MAL / e_Me_Kmal * (1 + MAL / e_Me_Kmal)^(e_Me_n - 1) / ((1 + MAL / e_Me_Kmal)^(e_Me_n) + e_Me_L * (1 + ACoA / e_Me_Kacoa + cAMP / e_Me_Kcamp)^(e_Me_n)))-1.0 * (Pdh * e_Pdh_kcat * PYR / e_Pdh_Kpyr * (1 + PYR / e_Pdh_Kpyr)^(e_Pdh_n - 1) / ((1 + PYR / e_Pdh_Kpyr)^(e_Pdh_n) + e_Pdh_L * (1 + GLX / e_Pdh_Kglx + PYR / e_Pdh_KpyrI)^(e_Pdh_n)))-1.0 * (PpsA * e_PpsA_kcat * PYR / e_PpsA_Kpyr * (1 + PYR / e_PpsA_Kpyr)^(e_PpsA_n - 1) / ((1 + PYR / e_PpsA_Kpyr)^(e_PpsA_n) + e_PpsA_L * (1 + PEP / e_PpsA_Kpep)^(e_PpsA_n)))+1.0 * (PykF * e_PykF_kcat * PEP / e_PykF_Kpep * (1 + PEP / e_PykF_Kpep)^(e_PykF_n - 1) / ((1 + PEP / e_PykF_Kpep)^(e_PykF_n) + e_PykF_L / (1 + FBP / e_PykF_Kfbp)^(e_PykF_n)))-1.0 * (mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * PYR),
D(Mdh) ~ +1.0 * (bm_k_expr * mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ((1 - CrpcAMP / (CrpcAMP + g_mdh_Kcrp)) * g_mdh_vcrp_unbound + CrpcAMP / (CrpcAMP + g_mdh_Kcrp) * g_mdh_vcrp_bound))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * Mdh),
D(Cra) ~ -1.0 * (tf_Cra_scale * ((Cra + CraFBP) * (FBP)^(tf_Cra_n) / ((FBP)^(tf_Cra_n) + (tf_Cra_kfbp)^(tf_Cra_n)) - CraFBP))+1.0 * (0)-1.0 * (0),
D(Icd_P) ~ +1.0 * (AceK * e_AceK_kcat_ki * Icd / e_AceK_Kicd * (1 + Icd / e_AceK_Kicd)^(e_AceK_n - 1) / ((1 + Icd / e_AceK_Kicd)^(e_AceK_n) + e_AceK_L * (1 + ICT / e_AceK_Kict + GLX / e_AceK_Kglx + OAA / e_AceK_Koaa + AKG / e_AceK_Kakg + PEP / e_AceK_Kpep + PG3 / e_AceK_Kpg3 + PYR / e_AceK_Kpyr)^(e_AceK_n)))-1.0 * (AceK * e_AceK_kcat_ph * Icd_P / e_AceK_Kicd_P * (1 + Icd_P / e_AceK_Kicd_P)^(e_AceK_n - 1) / ((1 + Icd_P / e_AceK_Kicd_P)^(e_AceK_n) + e_AceK_L / (1 + OAA / e_AceK_Koaa + AKG / e_AceK_Kakg + PEP / e_AceK_Kpep + PG3 / e_AceK_Kpg3 + PYR / e_AceK_Kpyr)^(e_AceK_n)))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * Icd_P),
D(Ppc) ~ +1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * SS_Ppc(GLC, pts_Kglc, ACT, e_Acs_Kact))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * Ppc),
D(PEP) ~ -1.0 * (k_bm_PEP(GLC, pts_Kglc, bm_GLC_PEP, ACT, e_Acs_Kact, bm_ACT_PEP) * PEP)-1.0 * (pts_k1 * PEP * EIIA - pts_km1 * PYR * EIIA_P)+1.0 * ((Eno * e_Eno_kcatf * PG3 / e_Eno_Kpg3 - Eno * e_Eno_kcatr * PEP / e_Eno_Kpep) / (1 + PG3 / e_Eno_Kpg3 + PEP / e_Eno_Kpep))+1.0 * (PckA * e_PckA_kcat * OAA / (OAA + e_PckA_Koaa * (1 + PEP / e_PckA_Kpep)))-1.0 * (Ppc * e_Ppc_kcat * PEP / e_Ppc_Kpep * (1 + PEP / e_Ppc_Kpep)^(e_Ppc_n - 1) / ((1 + PEP / e_Ppc_Kpep)^(e_Ppc_n) + e_Ppc_L / (1 + FBP / e_Ppc_Kfbp)^(e_Ppc_n)))+1.0 * (PpsA * e_PpsA_kcat * PYR / e_PpsA_Kpyr * (1 + PYR / e_PpsA_Kpyr)^(e_PpsA_n - 1) / ((1 + PYR / e_PpsA_Kpyr)^(e_PpsA_n) + e_PpsA_L * (1 + PEP / e_PpsA_Kpep)^(e_PpsA_n)))-1.0 * (PykF * e_PykF_kcat * PEP / e_PykF_Kpep * (1 + PEP / e_PykF_Kpep)^(e_PykF_n - 1) / ((1 + PEP / e_PykF_Kpep)^(e_PykF_n) + e_PykF_L / (1 + FBP / e_PykF_Kfbp)^(e_PykF_n)))-1.0 * (mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * PEP),
D(GLX) ~ +1.0 * (AceA * e_AceA_kcat * ICT / e_AceA_Kict * (1 + ICT / e_AceA_Kict)^(e_AceA_n - 1) / ((1 + ICT / e_AceA_Kict)^(e_AceA_n) + e_AceA_L * (1 + PEP / e_AceA_Kpep + PG3 / e_AceA_Kpg3 + AKG / e_AceA_Kakg)^(e_AceA_n)))-1.0 * (AceB * e_AceB_kcat * GLX * ACoA / (e_AceB_Kglxacoa * e_AceB_Kacoa + e_AceB_Kacoa * GLX + e_AceB_Kglx * ACoA + GLX * ACoA))-1.0 * (mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * GLX),
D(AceK) ~ +1.0 * (g_aceBAK_aceKfactor * bm_k_expr * mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ((1 - Cra / (Cra + g_aceBAK_Kcra)) * g_aceBAK_vcra_unbound + Cra / (Cra + g_aceBAK_Kcra) * g_aceBAK_vcra_bound + (1 - CrpcAMP / (CrpcAMP + g_aceBAK_Kcrp)) * g_aceBAK_vcrp_unbound + CrpcAMP / (CrpcAMP + g_aceBAK_Kcrp) * g_aceBAK_vcrp_bound + g_aceBAK_kcat_iclr * IclR * (1 - g_aceBAK_DNA / g_aceBAK_KDNA * (1 + PYR / g_aceBAK_KPprime) / (1 + GLX / g_aceBAK_KG * (1 + GLX / g_aceBAK_KG) / g_aceBAK_L + g_aceBAK_DNA / g_aceBAK_KDNA + PYR / g_aceBAK_KP + g_aceBAK_DNA * PYR / g_aceBAK_KDNA / g_aceBAK_KPprime))))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * AceK),
D(Me) ~ +1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * SS_Me(GLC, pts_Kglc, ACT, e_Acs_Kact))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * Me),
D(FBP) ~ -0.5 * ((Emp * e_Emp_kcat_f * FBP / e_Emp_Kfbp - Emp * e_Emp_kcat_r * PG3 / e_Emp_Kpg3) / (1 + FBP / e_Emp_Kfbp + PG3 / e_Emp_Kpg3))-1.0 * (Fdp * e_Fdp_kcat * FBP / e_Fdp_Kfbp * (1 + FBP / e_Fdp_Kfbp)^(e_Fdp_n - 1) / ((1 + FBP / e_Fdp_Kfbp)^(e_Fdp_n) + e_Fdp_L / (1 + PEP / e_Fdp_Kpep)^(e_Fdp_n)))+1.0 * (PfkA * e_PfkA_kcat * G6P / e_PfkA_Kg6p * (1 + G6P / e_PfkA_Kg6p)^(e_PfkA_n - 1) / ((1 + G6P / e_PfkA_Kg6p)^(e_PfkA_n) + e_PfkA_L * (1 + PEP / e_PfkA_Kpep)^(e_PfkA_n)))-1.0 * (mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * FBP),
D(GLC) ~ -1.0 * (env_uc * env_M_GLC * BM * pts_k4 * EIICB * EIIA_P * GLC / ((pts_KEIIA + EIIA_P) * (pts_Kglc + GLC))),
D(Cya) ~ +1.0 * (0)-1.0 * (0),
D(Acoa2act) ~ +1.0 * (0)-1.0 * (0),
D(BM) ~ +1.0 * (BM * mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT)),
D(ACT) ~ -1.0 * (env_uc * env_M_ACT * BM * Acs * e_Acs_kcat * ACT / (ACT + e_Acs_Kact))+1.0 * (env_uc * env_M_ACT * BM * Acoa2act * e_Acoa2act_kcat * ACoA / e_Acoa2act_Kacoa * (1 + ACoA / e_Acoa2act_Kacoa)^(e_Acoa2act_n - 1) / ((1 + ACoA / e_Acoa2act_Kacoa)^(e_Acoa2act_n) + e_Acoa2act_L / (1 + PYR / e_Acoa2act_Kpyr)^(e_Acoa2act_n))),
D(EIIA_P) ~ +1.0 * (pts_k1 * PEP * EIIA - pts_km1 * PYR * EIIA_P)-1.0 * (pts_k4 * EIICB * EIIA_P * GLC / ((pts_KEIIA + EIIA_P) * (pts_Kglc + GLC)))-1.0 * (0),
D(AKG) ~ -1.0 * (k_bm_AKG(GLC, pts_Kglc, bm_GLC_AKG, ACT, e_Acs_Kact, bm_ACT_AKG) * AKG)+1.0 * (AceA * e_AceA_kcat * ICT / e_AceA_Kict * (1 + ICT / e_AceA_Kict)^(e_AceA_n - 1) / ((1 + ICT / e_AceA_Kict)^(e_AceA_n) + e_AceA_L * (1 + PEP / e_AceA_Kpep + PG3 / e_AceA_Kpg3 + AKG / e_AceA_Kakg)^(e_AceA_n)))-1.0 * (Akg2mal * e_Akg2mal_kcat * AKG / (AKG + e_Akg2mal_Kakg))+1.0 * (Icd * e_Icd_kcat * ICT / e_Icd_Kict * (1 + ICT / e_Icd_Kict)^(e_Icd_n - 1) / ((1 + ICT / e_Icd_Kict)^(e_Icd_n) + e_Icd_L * (1 + PEP / e_Icd_Kpep)^(e_Icd_n)))-1.0 * (mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * AKG),
D(ICT) ~ -1.0 * (AceA * e_AceA_kcat * ICT / e_AceA_Kict * (1 + ICT / e_AceA_Kict)^(e_AceA_n - 1) / ((1 + ICT / e_AceA_Kict)^(e_AceA_n) + e_AceA_L * (1 + PEP / e_AceA_Kpep + PG3 / e_AceA_Kpg3 + AKG / e_AceA_Kakg)^(e_AceA_n)))+1.0 * (GltA * e_GltA_kcat * OAA * ACoA / ((1 + AKG / e_GltA_Kakg) * e_GltA_Koaaacoa * e_GltA_Kacoa + e_GltA_Kacoa * OAA + (1 + AKG / e_GltA_Kakg) * e_GltA_Koaa * ACoA + OAA * ACoA))-1.0 * (Icd * e_Icd_kcat * ICT / e_Icd_Kict * (1 + ICT / e_Icd_Kict)^(e_Icd_n - 1) / ((1 + ICT / e_Icd_Kict)^(e_Icd_n) + e_Icd_L * (1 + PEP / e_Icd_Kpep)^(e_Icd_n)))-1.0 * (mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ICT),
D(Fdp) ~ +1.0 * (bm_k_expr * mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ((1 - Cra / (Cra + g_fdp_Kcra)) * g_fdp_vcra_unbound + Cra / (Cra + g_fdp_Kcra) * g_fdp_vcra_bound))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * Fdp),
D(ACoA) ~ -1.0 * (k_bm_ACoA(GLC, pts_Kglc, bm_GLC_ACoA, ACT, e_Acs_Kact, bm_ACT_ACoA) * ACoA)-1.0 * (AceB * e_AceB_kcat * GLX * ACoA / (e_AceB_Kglxacoa * e_AceB_Kacoa + e_AceB_Kacoa * GLX + e_AceB_Kglx * ACoA + GLX * ACoA))-1.0 * (Acoa2act * e_Acoa2act_kcat * ACoA / e_Acoa2act_Kacoa * (1 + ACoA / e_Acoa2act_Kacoa)^(e_Acoa2act_n - 1) / ((1 + ACoA / e_Acoa2act_Kacoa)^(e_Acoa2act_n) + e_Acoa2act_L / (1 + PYR / e_Acoa2act_Kpyr)^(e_Acoa2act_n)))+1.0 * (Acs * e_Acs_kcat * ACT / (ACT + e_Acs_Kact))-1.0 * (GltA * e_GltA_kcat * OAA * ACoA / ((1 + AKG / e_GltA_Kakg) * e_GltA_Koaaacoa * e_GltA_Kacoa + e_GltA_Kacoa * OAA + (1 + AKG / e_GltA_Kakg) * e_GltA_Koaa * ACoA + OAA * ACoA))+1.0 * (Pdh * e_Pdh_kcat * PYR / e_Pdh_Kpyr * (1 + PYR / e_Pdh_Kpyr)^(e_Pdh_n - 1) / ((1 + PYR / e_Pdh_Kpyr)^(e_Pdh_n) + e_Pdh_L * (1 + GLX / e_Pdh_Kglx + PYR / e_Pdh_KpyrI)^(e_Pdh_n)))-1.0 * (mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ACoA),
D(GltA) ~ +1.0 * (bm_k_expr * mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ((1 - (CrpcAMP)^(g_gltA_n) / ((CrpcAMP)^(g_gltA_n) + (g_gltA_Kcrp)^(g_gltA_n))) * g_gltA_vcrp_unbound + (CrpcAMP)^(g_gltA_n) / ((CrpcAMP)^(g_gltA_n) + (g_gltA_Kcrp)^(g_gltA_n)) * g_gltA_vcrp_bound))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * GltA),
D(PdhRPYR) ~ +1.0 * (tf_PdhR_scale * ((PdhR + PdhRPYR) * (PYR)^(tf_PdhR_n) / ((PYR)^(tf_PdhR_n) + (tf_PdhR_kpyr)^(tf_PdhR_n)) - PdhRPYR))-1.0 * (0),
D(MAL) ~ +1.0 * (AceB * e_AceB_kcat * GLX * ACoA / (e_AceB_Kglxacoa * e_AceB_Kacoa + e_AceB_Kacoa * GLX + e_AceB_Kglx * ACoA + GLX * ACoA))+1.0 * (Akg2mal * e_Akg2mal_kcat * AKG / (AKG + e_Akg2mal_Kakg))-1.0 * (Mdh * e_Mdh_kcat * (MAL)^(e_Mdh_n) / ((MAL)^(e_Mdh_n) + (e_Mdh_Kmal)^(e_Mdh_n)))-1.0 * (Me * e_Me_kcat * MAL / e_Me_Kmal * (1 + MAL / e_Me_Kmal)^(e_Me_n - 1) / ((1 + MAL / e_Me_Kmal)^(e_Me_n) + e_Me_L * (1 + ACoA / e_Me_Kacoa + cAMP / e_Me_Kcamp)^(e_Me_n)))-1.0 * (mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * MAL),
D(Pdh) ~ +1.0 * (bm_k_expr * mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ((1 - PdhR / (PdhR + g_pdh_Kpdhr)) * g_pdh_vpdhr_unbound + PdhR / (PdhR + g_pdh_Kpdhr) * g_pdh_vpdhr_bound))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * Pdh),
D(Crp) ~ -1.0 * (tf_Crp_scale * ((Crp + CrpcAMP) * (cAMP)^(tf_Crp_n) / ((cAMP)^(tf_Crp_n) + (tf_Crp_kcamp)^(tf_Crp_n)) - CrpcAMP))+1.0 * (0)-1.0 * (0),
D(Akg2mal) ~ +1.0 * (bm_k_expr * mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ((1 - (CrpcAMP)^(g_akg2mal_n) / ((CrpcAMP)^(g_akg2mal_n) + (g_akg2mal_Kcrp)^(g_akg2mal_n))) * g_akg2mal_vcrp_unbound + (CrpcAMP)^(g_akg2mal_n) / ((CrpcAMP)^(g_akg2mal_n) + (g_akg2mal_Kcrp)^(g_akg2mal_n)) * g_akg2mal_vcrp_bound))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * Akg2mal),
D(PpsA) ~ +1.0 * (bm_k_expr * mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ((1 - Cra / (Cra + g_ppsA_Kcra)) * g_ppsA_vcra_unbound + Cra / (Cra + g_ppsA_Kcra) * g_ppsA_vcra_bound))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * PpsA),
D(G6P) ~ -1.0 * (k_bm_G6P(GLC, pts_Kglc, bm_GLC_G6P, ACT, e_Acs_Kact, bm_ACT_G6P) * G6P)+1.0 * (pts_k4 * EIICB * EIIA_P * GLC / ((pts_KEIIA + EIIA_P) * (pts_Kglc + GLC)))+1.0 * (Fdp * e_Fdp_kcat * FBP / e_Fdp_Kfbp * (1 + FBP / e_Fdp_Kfbp)^(e_Fdp_n - 1) / ((1 + FBP / e_Fdp_Kfbp)^(e_Fdp_n) + e_Fdp_L / (1 + PEP / e_Fdp_Kpep)^(e_Fdp_n)))-1.0 * (PfkA * e_PfkA_kcat * G6P / e_PfkA_Kg6p * (1 + G6P / e_PfkA_Kg6p)^(e_PfkA_n - 1) / ((1 + G6P / e_PfkA_Kg6p)^(e_PfkA_n) + e_PfkA_L * (1 + PEP / e_PfkA_Kpep)^(e_PfkA_n)))-1.0 * (mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * G6P),
D(PckA) ~ +1.0 * (bm_k_expr * mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ((1 - Cra / (Cra + g_pckA_Kcra)) * g_pckA_vcra_unbound + Cra / (Cra + g_pckA_Kcra) * g_pckA_vcra_bound))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * PckA),
D(CraFBP) ~ +1.0 * (tf_Cra_scale * ((Cra + CraFBP) * (FBP)^(tf_Cra_n) / ((FBP)^(tf_Cra_n) + (tf_Cra_kfbp)^(tf_Cra_n)) - CraFBP))-1.0 * (0),
D(Icd) ~ -1.0 * (AceK * e_AceK_kcat_ki * Icd / e_AceK_Kicd * (1 + Icd / e_AceK_Kicd)^(e_AceK_n - 1) / ((1 + Icd / e_AceK_Kicd)^(e_AceK_n) + e_AceK_L * (1 + ICT / e_AceK_Kict + GLX / e_AceK_Kglx + OAA / e_AceK_Koaa + AKG / e_AceK_Kakg + PEP / e_AceK_Kpep + PG3 / e_AceK_Kpg3 + PYR / e_AceK_Kpyr)^(e_AceK_n)))+1.0 * (AceK * e_AceK_kcat_ph * Icd_P / e_AceK_Kicd_P * (1 + Icd_P / e_AceK_Kicd_P)^(e_AceK_n - 1) / ((1 + Icd_P / e_AceK_Kicd_P)^(e_AceK_n) + e_AceK_L / (1 + OAA / e_AceK_Koaa + AKG / e_AceK_Kakg + PEP / e_AceK_Kpep + PG3 / e_AceK_Kpg3 + PYR / e_AceK_Kpyr)^(e_AceK_n)))+1.0 * (bm_k_expr * mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ((1 - Cra / (Cra + g_icd_Kcra)) * g_icd_vcra_unbound + Cra / (Cra + g_icd_Kcra) * g_icd_vcra_bound))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * Icd),
D(PykF) ~ +1.0 * (bm_k_expr * mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ((1 - Cra / (Cra + g_pykF_Kcra)) * g_pykF_vcra_unbound + Cra / (Cra + g_pykF_Kcra) * g_pykF_vcra_bound))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * PykF),
D(EIIA) ~ -1.0 * (pts_k1 * PEP * EIIA - pts_km1 * PYR * EIIA_P)+1.0 * (pts_k4 * EIICB * EIIA_P * GLC / ((pts_KEIIA + EIIA_P) * (pts_Kglc + GLC)))+1.0 * (0)-1.0 * (0),
D(PG3) ~ -1.0 * (k_bm_PG3(GLC, pts_Kglc, bm_GLC_PG3, ACT, e_Acs_Kact, bm_ACT_PG3) * PG3)+1.0 * ((Emp * e_Emp_kcat_f * FBP / e_Emp_Kfbp - Emp * e_Emp_kcat_r * PG3 / e_Emp_Kpg3) / (1 + FBP / e_Emp_Kfbp + PG3 / e_Emp_Kpg3))-1.0 * ((Eno * e_Eno_kcatf * PG3 / e_Eno_Kpg3 - Eno * e_Eno_kcatr * PEP / e_Eno_Kpep) / (1 + PG3 / e_Eno_Kpg3 + PEP / e_Eno_Kpep))-1.0 * (mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * PG3),
D(PfkA) ~ +1.0 * (bm_k_expr * mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ((1 - Cra / (Cra + g_pfkA_Kcra)) * g_pfkA_vcra_unbound + Cra / (Cra + g_pfkA_Kcra) * g_pfkA_vcra_bound))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * PfkA),
D(IclR) ~ +1.0 * (0)-1.0 * (0),
D(PdhR) ~ -1.0 * (tf_PdhR_scale * ((PdhR + PdhRPYR) * (PYR)^(tf_PdhR_n) / ((PYR)^(tf_PdhR_n) + (tf_PdhR_kpyr)^(tf_PdhR_n)) - PdhRPYR))+1.0 * (0)-1.0 * (0),
D(CrpcAMP) ~ +1.0 * (tf_Crp_scale * ((Crp + CrpcAMP) * (cAMP)^(tf_Crp_n) / ((cAMP)^(tf_Crp_n) + (tf_Crp_kcamp)^(tf_Crp_n)) - CrpcAMP))-1.0 * (0),
D(AceA) ~ +1.0 * (bm_k_expr * mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ((1 - Cra / (Cra + g_aceBAK_Kcra)) * g_aceBAK_vcra_unbound + Cra / (Cra + g_aceBAK_Kcra) * g_aceBAK_vcra_bound + (1 - CrpcAMP / (CrpcAMP + g_aceBAK_Kcrp)) * g_aceBAK_vcrp_unbound + CrpcAMP / (CrpcAMP + g_aceBAK_Kcrp) * g_aceBAK_vcrp_bound + g_aceBAK_kcat_iclr * IclR * (1 - g_aceBAK_DNA / g_aceBAK_KDNA * (1 + PYR / g_aceBAK_KPprime) / (1 + GLX / g_aceBAK_KG * (1 + GLX / g_aceBAK_KG) / g_aceBAK_L + g_aceBAK_DNA / g_aceBAK_KDNA + PYR / g_aceBAK_KP + g_aceBAK_DNA * PYR / g_aceBAK_KDNA / g_aceBAK_KPprime))))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * AceA),
D(Acs) ~ +1.0 * (bm_k_expr * mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ((1 - (CrpcAMP)^(g_acs_n) / ((CrpcAMP)^(g_acs_n) + (g_acs_Kcrp)^(g_acs_n))) * g_acs_vcrp_unbound + (CrpcAMP)^(g_acs_n) / ((CrpcAMP)^(g_acs_n) + (g_acs_Kcrp)^(g_acs_n)) * g_acs_vcrp_bound))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * Acs),
D(Emp) ~ +1.0 * (bm_k_expr * mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ((1 - Cra / (Cra + g_emp_Kcra)) * g_emp_vcra_unbound + Cra / (Cra + g_emp_Kcra) * g_emp_vcra_bound + (1 - CrpcAMP / (CrpcAMP + g_emp_Kcrp)) * g_emp_vcrp_unbound + CrpcAMP / (CrpcAMP + g_emp_Kcrp) * g_emp_vcrp_bound))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * Emp),
D(AceB) ~ +1.0 * (g_aceBAK_aceBfactor * bm_k_expr * mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) * ((1 - Cra / (Cra + g_aceBAK_Kcra)) * g_aceBAK_vcra_unbound + Cra / (Cra + g_aceBAK_Kcra) * g_aceBAK_vcra_bound + (1 - CrpcAMP / (CrpcAMP + g_aceBAK_Kcrp)) * g_aceBAK_vcrp_unbound + CrpcAMP / (CrpcAMP + g_aceBAK_Kcrp) * g_aceBAK_vcrp_bound + g_aceBAK_kcat_iclr * IclR * (1 - g_aceBAK_DNA / g_aceBAK_KDNA * (1 + PYR / g_aceBAK_KPprime) / (1 + GLX / g_aceBAK_KG * (1 + GLX / g_aceBAK_KG) / g_aceBAK_L + g_aceBAK_DNA / g_aceBAK_KDNA + PYR / g_aceBAK_KP + g_aceBAK_DNA * PYR / g_aceBAK_KDNA / g_aceBAK_KPprime))))-1.0 * ((mu(GLC, pts_Kglc, bm_muGLC, ACT, e_Acs_Kact, bm_muACT) + d_k_degr) * AceB)]

@named sys = ODESystem(eqs, t, continuous_events = continuous_events)

### Initial species concentrations ###
initialSpeciesValues = [
CAMPdegr => 0.001,
EIICB => 0.003,
cAMP => 0.202804098,
OAA => 0.050535354,
Eno => 0.011552813,
PYR => 0.863278018,
Mdh => 0.00345727,
Cra => 0.000299098,
Icd_P => 0.000220477,
Ppc => 0.000999714,
PEP => 0.210455879,
GLX => 5.70593e-9,
AceK => 0.000141697,
Me => 0.000999714,
FBP => 6.57504207,
GLC => 4.8,
Cya => 0.001,
Acoa2act => 0.001,
BM => 0.03,
ACT => 0.0,
EIIA_P => 0.00352292,
AKG => 0.191190619,
ICT => 0.001408116,
Fdp => 0.000157492,
ACoA => 0.351972298,
GltA => 0.001029612,
PdhRPYR => 0.006126187,
MAL => 3.278779135,
Pdh => 0.004647401,
Crp => 0.005943273,
Akg2mal => 0.001026848,
PpsA => 0.000987493,
G6P => 1.908140784,
PckA => 0.002290892,
CraFBP => 0.006990902,
Icd => 0.004290789,
PykF => 0.005977168,
EIIA => 0.09647707,
PG3 => 5.720977255,
PfkA => 0.000143816,
IclR => 0.00729,
PdhR => 0.001163813,
CrpcAMP => 0.001346727,
AceA => 0.00472323,
Acs => 0.001096222,
Emp => 0.011515593,
AceB => 0.001416969]

### True parameter values ###
trueParameterValues = [
e_AceK_Kpyr => 0.038,
e_CAMPdegr_kcat => 1000.0,
g_emp_Kcrp => 0.012,
e_PpsA_L => 1.0e-79,
e_Acs_Kact => 0.001,
e_Icd_kcat => 695.0,
g_akg2mal_n => 0.74,
e_Pdh_L => 3.4,
g_pykF_vcra_bound => 2.1e-9,
e_Icd_Kict => 0.00016,
g_ppsA_Kcra => 0.017,
e_PfkA_L => 9.5e7,
g_pfkA_vcra_bound => 6.6e-9,
g_ppsA_vcra_bound => 3.3e-6,
e_Ppc_Kfbp => 0.408,
bm_ACT_PYR => 5.185,
g_aceBAK_DNA => 1.0,
bm_GLC_OAA => 6.4,
e_Ppc_L => 5.2e6,
e_Mdh_Kmal => 10.1,
bm_GLC_AKG => 0.978,
g_icd_vcra_bound => 8.5e-7,
g_mdh_vcrp_bound => 9.1e-6,
g_aceBAK_kcat_iclr => 0.00093,
bm_muACT => 5.6e-5,
g_mdh_vcrp_unbound => 0.0,
e_Eno_Kpep => 1.11,
e_AceB_Kglx => 0.95,
e_Acoa2act_Kpyr => 0.022,
e_AceK_kcat_ph => 1.7e9,
e_AceK_Kpep => 0.539,
bm_ACT_PEP => 0.047,
bm_GLC_G6P => 0.154,
e_Pdh_KpyrI => 0.231,
g_akg2mal_vcrp_unbound => 0.0,
e_Me_kcat => 1879.0,
g_fdp_Kcra => 0.00118,
tf_PdhR_kpyr => 0.164,
e_GltA_Kacoa => 0.212,
e_Mdh_kcat => 773.0,
e_AceK_kcat_ki => 3.4e12,
e_Eno_Kpg3 => 4.76,
e_AceK_Kict => 0.137,
e_CAMPdegr_KcAMP => 0.1,
e_AceK_Koaa => 0.173,
g_mdh_Kcrp => 0.06,
g_pdh_vpdhr_unbound => 3.6e-7,
e_AceK_Kakg => 0.82,
e_PckA_Koaa => 0.184,
e_PckA_Kpep => 1000.0,
pts_km1 => 46.3,
g_aceBAK_Kcra => 0.00365,
e_AceB_Kacoa => 0.755,
env_M_GLC => 180.156,
g_pdh_vpdhr_bound => 1.3e-9,
e_Icd_L => 127.0,
g_akg2mal_Kcrp => 0.091,
e_Me_Kmal => 0.00624,
e_AceB_kcat => 47.8,
g_pfkA_vcra_unbound => 8.2e-7,
e_Eno_kcatf => 695.0,
e_PfkA_kcat => 908000.0,
GLC_2 => 3.0,
e_Fdp_n => 4.0,
g_aceBAK_aceKfactor => 0.03,
e_Icd_Kpep => 0.334,
g_gltA_vcrp_bound => 2.3e-6,
e_Acs_kcat => 340.0,
g_aceBAK_vcrp_bound => 2.3e-10,
g_icd_Kcra => 0.00117,
GLC_1 => 0.0,
e_AceA_Kict => 0.022,
e_Mdh_n => 1.7,
e_Ppc_n => 3.0,
e_Fdp_L => 4.0e6,
e_Me_Kacoa => 3.64,
g_emp_vcra_unbound => 6.2e-7,
e_Cya_kcat => 993.0,
g_acs_n => 2.31,
e_PykF_Kfbp => 0.413,
g_icd_vcra_unbound => 1.1e-7,
e_AceA_L => 50100.0,
e_AceA_Kpg3 => 0.72,
bm_ACT_G6P => 0.076,
bm_GLC_PG3 => 0.049,
g_aceBAK_Kcrp => 0.341,
g_eno_Kcra => 0.016,
g_pykF_vcra_unbound => 3.9e-7,
g_emp_Kcra => 0.09,
bm_GLC_ACoA => 1.88,
e_Me_n => 1.33,
g_aceBAK_aceBfactor => 0.3,
e_Icd_n => 2.0,
g_emp_vcrp_bound => 4.7e-7,
e_Emp_kcat_r => 848.0,
g_aceBAK_KDNA => 2.19,
g_aceBAK_L => 923.0,
e_Acoa2act_kcat => 3079.0,
bm_ACT_PG3 => 0.066,
e_Me_Kcamp => 6.54,
pts_KEIIA => 0.0085,
e_Fdp_Kpep => 0.3,
BM_2 => 0.0005,
ACT_1 => 5.0,
e_AceA_n => 4.0,
e_AceB_Kglxacoa => 0.719,
pts_Kglc => 0.0012,
e_AceK_Kpg3 => 1.57,
g_aceBAK_KG => 0.00488,
e_Pdh_Kpyr => 0.128,
e_Acoa2act_L => 639000.0,
g_eno_vcra_unbound => 6.8e-7,
e_AceK_Kicd => 0.043,
g_acs_Kcrp => 0.0047,
e_AceK_n => 2.0,
bm_ACT_AKG => 0.056,
bm_GLC_PYR => 0.553,
e_PckA_kcat => 55.5,
e_AceA_kcat => 614.0,
e_PykF_L => 100000.0,
tf_Cra_scale => 100.0,
ACT_2 => 3.0,
e_PykF_n => 4.0,
g_pckA_Kcra => 0.00535,
g_gltA_Kcrp => 0.04,
e_PpsA_n => 2.0,
tf_PdhR_scale => 100.0,
g_aceBAK_KPprime => 0.00301,
g_fdp_vcra_unbound => 0.0,
BM_1 => 0.03,
g_ppsA_vcra_unbound => 0.0,
g_pykF_Kcra => 0.0023,
e_Emp_Kpg3 => 16.6,
g_gltA_n => 1.07,
e_PykF_Kpep => 5.0,
bm_GLC_PEP => 0.423,
g_aceBAK_vcrp_unbound => 2.0e-8,
e_PfkA_Kg6p => 0.022,
e_Cya_KEIIA => 0.0017,
e_Acoa2act_n => 2.0,
e_Emp_kcat_f => 1000.0,
g_aceBAK_vcra_unbound => 1.9e-9,
e_Ppc_kcat => 5635.0,
e_GltA_Koaaacoa => 0.029,
tf_Crp_kcamp => 0.895,
env_uc => 9.5e-7,
g_akg2mal_vcrp_bound => 1.4e-6,
e_AceA_Kakg => 0.827,
e_PpsA_Kpyr => 0.00177,
e_AceK_Kicd_P => 0.643,
g_pckA_vcra_bound => 2.5e-6,
e_Fdp_Kfbp => 0.003,
e_AceK_L => 1.0e8,
g_emp_vcrp_unbound => 0.0,
e_Akg2mal_kcat => 1530.0,
e_GltA_Koaa => 0.029,
e_Me_L => 104000.0,
tf_Cra_n => 2.0,
g_emp_vcra_bound => 0.0,
e_Pdh_kcat => 1179.0,
e_Akg2mal_Kakg => 0.548,
g_pckA_vcra_unbound => 0.0,
e_Ppc_Kpep => 0.048,
e_Pdh_n => 2.65,
bm_ACT_OAA => 1.43,
bm_k_expr => 20000.0,
g_pfkA_Kcra => 6.3e-7,
e_Eno_kcatr => 522.0,
tf_Cra_kfbp => 1.36,
e_Emp_Kfbp => 5.92,
g_fdp_vcra_bound => 4.5e-8,
e_PykF_kcat => 5749.0,
e_PfkA_n => 4.0,
g_pdh_Kpdhr => 0.0034,
g_acs_vcrp_bound => 1.2e-6,
pts_k1 => 116.0,
tf_Crp_scale => 1.0e8,
tf_PdhR_n => 1.0,
g_acs_vcrp_unbound => 0.0,
env_M_ACT => 60.05,
e_AceK_Kglx => 0.866,
e_GltA_Kakg => 0.63,
pts_k4 => 2520.0,
e_Fdp_kcat => 192.0,
tf_Crp_n => 1.0,
g_eno_vcra_bound => 0.0,
bm_muGLC => 0.00018,
g_aceBAK_KP => 0.897,
shift1 => 8.15,
e_PfkA_Kpep => 0.138,
g_gltA_vcrp_unbound => 0.0,
d_k_degr => 2.8e-5,
e_PpsA_Kpep => 0.001,
bm_ACT_ACoA => 0.108,
e_PpsA_kcat => 1.32,
e_AceA_Kpep => 0.055,
g_aceBAK_vcra_bound => 2.0e-6,
shift2 => 27.85,
e_Acoa2act_Kacoa => 0.022,
e_GltA_kcat => 1614.0,
e_Pdh_Kglx => 0.218]

trueConstantsValues = [
Environment => 1.0,
Cell => 1.0]
